### ISSUE TITLE
Changing my ngrok Authtoken

### ISSUE THREAD

**Issue by jamie20021234** [HiDe-Techno-Tips/Blackeye-for-Windows#25] opened 2022-06-28 21:51 UTC
My Ngrok got banned after a couple minutes, How do i Begin the process with blackeye from the beginning so i can put in the new Authtoken? I've tried deleting and re downloading...

**Comment by HimDek** [comment] 2022-06-29 04:09
Duplicate of #24

**Closed as completed by HimDek** 2022-06-29 04:09 UTC
